### ISSUE TITLE
RandomForestRegressior

### ISSUE THREAD

**Issue by MichaelSchroter** [garethjns/IncrementalTrees#2]
Hi,

Will it be possible to do a random forest regressor along with the random forest classifier

Thanks

Michael

**Comment by garethjns** [comment]
Hi Micheal,

I'm actually working on this at the moment. I've pushed to this branch https://github.com/garethjns/IncrementalTrees/tree/regressors if you want to give it a try.  I haven't done much testing yet, and there are few outstanding issues, like unexpected numbers of estimators being fit in the regressor ensembles. So expect bugs!

**Comment by garethjns** [comment]
Regressors are now available in v0.3+
